### ISSUE TITLE
MEASURES_AND_ISSUES delta - errors in the calculation

### ISSUE THREAD

**Issue by davidetaibi** [pervcomp/SonarQube-Faults-commit-mapping#1]
Il file measure and issue di Guvs non e' corretto. 

Il file con i delta (che d'ora in poi potremmo chiamare SONAR_ADDED_REMOVED_ISSUES) dovrebbe essere calculato da capo, a partire dal file "SONAR_ISSUE" (o dalla tabella SQL relativa). 

Il file deve essere sempre identico al precedente, ma senza metriche (le metriche sono gia' in SONAR_MEASURES"). 

Crea un file csv che contenga le stesse righe del  "sonar_measure"  (solo le prime 2 colonne) e il numero di issues aggiunte o rimosse in quella commit

Esempio di file  SONAR_ADDED_REMOVED_ISSUES 

**PROJECT-ID, COMMIT_SHA, MEASURE-DATE, ADDED_SQUID:00112, REMOVED_SQUID:00112, TOT_SQUID:00112, ADDED_SQUID:...**  

L'elenco delle issues lo ottieni con la query: 
select distinct rule from sonar_Issues order by rule

Il count della colonna "**ADDED**" lo ottieni (passando il corretto nome della rule e project-id e measure-date" con la query

select count("measure-date") as '**squid:S00122**', PROJECT_ID   from sonar_issues where rule='**squid:S00122**' and 
creationDate='**2003-09-04T23:28:19Z**' and sonar_issues.PROJECT_ID='**org-apache-daemon**'

Il count della colonna "**REMOVED**" lo ottieni
select count("measure-date") as '**squid:S00122**', PROJECT_ID   from sonar_issues where rule='**squid:S00122**' and 
closeDate='**2003-09-04T23:28:19Z**' and sonar_issues.PROJECT_ID='**org-apache-daemon**'

Il problema principale e' calcolare il TOT. che purtroppo va calcolato a mano. Ci saranno molte commit in cui non ci sono added ne removed, e di conseguenza il TOT rimarra' invariato rispetto alla commit precedente. 

Fai attenzione alle performance dell'algoritmo. Potrebbero volerci giorni se non e' ben ottimizzato.

**Comment by luca9294** [comment]
Ciao @davidetaibi , trova quindi l sqllite nello scheduler giusto?

**Comment by davidetaibi** [comment]
OPPS, ... ti condivido subito il file...

**Comment by luca9294** [comment]
@davidetaibi  non posso fare per il TOT = ADDED-REMOVED? o come deve essere esattamente TOT?

**Comment by luca9294** [comment]
@davidetaibi utilizzando 10 Threads ci ha messo circa 8 ore per calculare i delta di goni progetto. 
I code smells ora sono inclusi
